#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Sara/Sara.csproj", "Sara/"]
RUN dotnet restore "Sara/Sara.csproj"
COPY . .
WORKDIR "/src/Sara"
RUN dotnet build "Sara.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Sara.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Sara.dll"]